<div class="t_g_tab">
	<div><img src="<?php echo $this->APP_STATIC_SERVER; ?>/skin/<?php echo $this->APP_TEMPLATE; ?>/<?php echo $this->APP_SKIN; ?>/images/ck1.jpg" /></div>
	<div id="tStockTableTabs">
		<ul>
			<li><a rel="HCMS" href="#tStockHCMSTab"><span><?php echo $this->translator()->widget('hcms'); ?></span></a></li>
			<li><a rel="HNX" href="#tStockHNXTab"><span><?php echo $this->translator()->widget('hnx'); ?></span></a></li>
		</ul>
		<div id="tStockHCMSTab"></div>
		<div id="tStockHNXTab"></div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function() {
	$('#tStockTableTabs').find('li').each(function() {
		var self = this;
		var a = $(self).children('a:first');
		$(a).click(function() {
			var code = $(this).attr('rel'); 
			Tomato.Modules.Ultility.Widgets.Stock.loadStock(code);
		});	
	});
	$('#tStockTableTabs').find('li:first').children('a:first').click();
	$('#tStockTableTabs').tabs();
});
'Tomato.Modules.Ultility.Widgets.Stock'.namespace();
Tomato.Modules.Ultility.Widgets.Stock.loadStock = function(code) {
	switch (code) {
		case 'HCMS':
			url = 'http://vnexpress.net/User/ck/Source/GetHCMSDataSmall.asp?x=';
			break;
		case 'HNX':
			url = 'http://vnexpress.net/User/ck/Source/GetHNSDataSmall.asp?x=';
			break;
	}
	var container = 'tStock' + code + 'Tab';
	var data = '{ "url": "' + url.concat((new Date()).getTime()) + '"}';
	var response = Tomato.Core.Widget.Loader.queueAction('utility', 'stock', 'load', data, container);
};
</script>
<style type="text/css">
#tblSmallSource { border: #ccc 1px solid; width: 100%;; border-collapse: collapse; }
.t_g_tab .ui-widget { font-size: 11px; }
.t_g_tab .ui-tabs { border: none; border-width: 0; padding: 0; }
.t_g_tab .ui-corner-all { -moz-border-radius: 0px; -webkit-border-radius: 0px }
.t_g_tab .ui-tabs .ui-tabs-nav { background: none; border-top: none; border-left: none; border-right: none; }
.t_g_tab .ui-tabs .ui-tabs-panel { padding-left: 0; padding-right: 0; border-width: 0; }
.t_g_tab .ui-widget-content { border: none; background: none; padding: 5px; }
.t_g_tab .ui-state-active { background-image: none; background-color: #F9F9F9; }

.S {FONT-SIZE: 8pt; BACKGROUND: #FFFFFF; COLOR: #000000; FONT-FAMILY: 'Arial'; TEXT-ALIGN: left; font-weight:bold;}
.V {FONT-SIZE: 8pt; BACKGROUND: #FFFFFF; COLOR: #000000; FONT-FAMILY: 'Arial'; TEXT-ALIGN: right;}
.S2{FONT-WEIGHT: bold; FONT-SIZE: 12pt;  COLOR: #F7FF31; FONT-FAMILY: 'Arial'; TEXT-ALIGN: left}
.ST{FONT-SIZE: 10pt;  COLOR: #a5a3a3; FONT-FAMILY: 'Arial'; TEXT-ALIGN: left}
.C {FONT-SIZE: 10pt;  COLOR: #FF00FF; FONT-FAMILY: 'Arial'; TEXT-ALIGN: right}
.F {FONT-SIZE: 10pt;  COLOR: #66CCFF; FONT-FAMILY: 'Arial'; TEXT-ALIGN: right}
.Y {FONT-SIZE: 8pt;  COLOR: #F7FF31; FONT-FAMILY: 'Arial'; TEXT-ALIGN: right; BACKGROUND:#999999;}
.R {FONT-SIZE: 8pt;  COLOR: #FF0000; FONT-FAMILY: 'Arial'; TEXT-ALIGN: right; BACKGROUND:#999999;}
.G {FONT-SIZE: 8pt;  COLOR: #00FF00; FONT-FAMILY: 'Arial'; TEXT-ALIGN: right; BACKGROUND:#999999;}
.W {FONT-SIZE: 10pt;  COLOR: #FFFFFF; FONT-FAMILY: 'Arial'; TEXT-ALIGN: right}
.AP{FONT-WEIGHT: bold; FONT-SIZE: 12pt;  COLOR: #F7FF31; FONT-FAMILY: 'Arial'; TEXT-ALIGN: right}
.T {FONT-WEIGHT: bold; FONT-SIZE: 12pt;  COLOR: #00FF00; FONT-FAMILY: 'Arial'; TEXT-ALIGN: left}
.AL{FONT-SIZE: 10pt;  COLOR: #F7FF31; FONT-FAMILY: 'Arial'; TEXT-ALIGN: left}
.ALB{FONT-WEIGHT: bold; FONT-SIZE: 10pt;  COLOR: #00FF00; FONT-FAMILY: 'Arial'; TEXT-ALIGN: left}
.ALR{FONT-WEIGHT: normal; FONT-SIZE: 10pt;  COLOR: #00FF00; FONT-FAMILY: 'Arial'; TEXT-ALIGN: left}
.ACB{FONT-WEIGHT: bold; FONT-SIZE: 10pt;  COLOR: #00FF00; FONT-FAMILY: 'Arial'; TEXT-ALIGN: center}
.AR{FONT-SIZE: 10pt;  COLOR: #00FF00; FONT-FAMILY: 'Arial'; TEXT-ALIGN: Right}
.ARB{FONT-WEIGHT: bold; FONT-SIZE: 10pt;  COLOR: #00FF00; FONT-FAMILY: 'Arial'; TEXT-ALIGN: Right}
.Box {FONT-WEIGHT: bold; FONT-SIZE: 12pt;  COLOR: #a5a3a3; FONT-FAMILY: 'Arial'; TEXT-ALIGN: left}
.Norm {FONT-SIZE: 10pt;  COLOR: #a5a3a3; FONT-FAMILY: 'Arial'; TEXT-ALIGN: left}
.REF{text-decoration: none; FONT-WEIGHT: bold; FONT-SIZE: 22pt;  COLOR: #F7FF31; FONT-FAMILY: 'Arial'}
	
.MarqueeDate 	{font-size: 10pt;  color: #9d0000; font-family: 'arial'; padding: 0 8 0 8 }
.MarqueePoint 	{font-size: 10pt;  color: #015396; font-family: 'arial'; padding: 0 8 0 8 }
.MarqueeQuantity{font-size: 10pt;  color: #ffffff; font-family: 'arial'; padding: 0 8 0 8 }
.MarqueeValue 	{font-size: 10pt;  color: #ffffff; font-family: 'arial'; padding: 0 8 0 8 }
.MarqueeVolumn 	{font-size: 10pt;  color: #ffffff; font-family: 'arial'; padding: 0 8 0 8 }

.cTableCheckBox	{BORDER: 1px solid #6c7170; BORDER-COLLAPSE: collapse; background-color: #000000}
.cTextCheckBox	{font-family:Courier New; font-size:14px; font-weight:bold; color: #adadad;}
.cTableSmall {BORDER: 1px solid #666666; background: #FFFFFF; border-collapse:collapse;}

.cTableQuote	{BORDER-TOP-WIDTH: 3px; BORDER-BOTTOM-WIDTH: 3px; BORDER-COLLAPSE: collapse; border-color:#6c7170} 
.cTableHeader	{font-family:tahoma; font-size:8pt; font-weight:bold; color: #f7ff31; border-color:#6c7170}
.cTableHeaderB	{font-family:tahoma; font-size:8pt; font-weight:bold; color: #f7ff31; BORDER-TOP-WIDTH: 3px; BORDER-RIGHT-WIDTH: 3px; BORDER-LEFT-WIDTH: 3px; text-align:center; border-color:#6c7170}
.cTableHeaderS	{font-family:tahoma; font-size:8pt; font-weight:bold; color: #f7ff31; BORDER-TOP-WIDTH: 3px; BORDER-RIGHT-WIDTH: 3px; BORDER-LEFT-WIDTH: 3px; text-align:center; border-color:#6c7170}
.cTableHeaderT	{font-family:tahoma; font-size:8pt; font-weight:bold; color: #f7ff31; BORDER-TOP-WIDTH: 3px; BORDER-RIGHT-WIDTH: 3px; BORDER-LEFT-WIDTH: 3px; text-align:center; border-color:#6c7170}
.cTableHeader1	{font-family:tahoma; font-size:8pt; font-weight:bold; color: #f7ff31; BORDER-TOP-WIDTH: 3px; text-align:center; border-color:#6c7170}
.cTableHeader2	{font-family:tahoma; font-size:8pt; font-weight:bold; color: #f7ff31; BORDER-RIGHT-WIDTH: 3px; text-align:center; border-color:#6c7170}
.cTableHeader3	{font-family:tahoma; font-size:8pt; font-weight:bold; color: #f7ff31; BORDER-BOTTOM-WIDTH: 3px; text-align:center; border-color:#6c7170}
.cTableHeader4	{font-family:tahoma; font-size:8pt; font-weight:bold; color: #f7ff31; BORDER-LEFT-WIDTH: 3px; text-align:center; border-color:#6c7170}
.cTableHeader5	{font-family:tahoma; font-size:8pt; font-weight:bold; color: #f7ff31; BORDER-WIDTH: 3px; Text-align:center; border-color:#6c7170}
.cTableHeader34	{font-family:tahoma; font-size:8pt; font-weight:bold; color: #f7ff31;  BORDER-BOTTOM-WIDTH: 3px; BORDER-LEFT-WIDTH: 3px; text-align:center; border-color:#6c7170}
.cTableHeader32	{font-family:tahoma; font-size:8pt; font-weight:bold; color: #f7ff31;  BORDER-BOTTOM-WIDTH: 3px; BORDER-RIGHT-WIDTH: 3px; text-align:center; border-color:#6c7170}

.cColumnTotal	{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:bold; color: #ffffff; border-color:#6c7170}
.cColumnQuantiyN{font-family:tahoma; text-align:right; padding: 0 2 0 2; font-size:8pt; font-weight:bold; color: #003062; border-color:#6c7170}

.cRowOdd		{font-family:tahoma; font-size:8pt; font-weight:bold; background-color: #f1f4f9; text-align:right; padding: 0 2 0 2;}
.cRowEven		{font-family:tahoma; font-size:8pt; font-weight:bold; background-color: #ffffff; text-align:right; padding: 0 2 0 2;}

.cColumnCode	{font-family:Courier New; font-size:14px; font-weight:bold; text-align:left; padding: 0 2 0 6; color: #f7ff31;  BORDER-RIGHT-WIDTH: 3px; border-color:#6c7170}
.cColumnMedium	{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #f7ff31; border-color:#6c7170}
.cColumnMax		{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #ff00ff; border-color:#6c7170}
.cColumnMin		{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #66ccff; border-color:#6c7170}
.cColumnQuantiy	{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #003062; border-color:#6c7170}
.cColumnPositive{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #00ff00; border-color:#6c7170}
.cColumnMinus	{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #ff0000; border-color:#6c7170}
.cColumnFixed	{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #f7ff31; border-color:#6c7170}
.cColumnFixedN	{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #f7ff31; border-color:#6c7170}
.cColumnFixedH	{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #f7ff31; border-color:#6c7170}
.cColumnData	{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #ffffff; border-color:#6c7170}	
.cColumnDataN	{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #ffffff; border-color:#6c7170}
.cColumnDataB	{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #ffffff; border-color:#6c7170}

.cColumnMediumN	{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #f7ff31; border-color:#6c7170}
.cColumnMaxN	{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #ff00ff; border-color:#6c7170}
.cColumnMinN	{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #66ccff; border-color:#6c7170}
.cColumnPositiveN{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #00ff00; border-color:#6c7170}
.cColumnMinusN	{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #ff0000; border-color:#6c7170}

.cColumnTMediumN	{font-family:tahoma; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:bold; color: #f7ff31; border-color:#6c7170}
.cColumnTMaxN	{font-family:tahoma; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:bold; color: #ff00ff; border-color:#6c7170}
.cColumnTMinN	{font-family:tahoma; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:bold; color: #66ccff; border-color:#6c7170}
.cColumnTPositiveN{font-family:tahoma; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:bold; color: #00ff00; border-color:#6c7170}
.cColumnTMinusN	{font-family:tahoma; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:bold; color: #ff0000; border-color:#6c7170}
.cColumnTFixedN	{font-family:tahoma; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:bold; color: #f7ff31; border-color:#6c7170}

.cColumnMediumB	{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal;  color: #f7ff31; border-color:#6c7170; background-color: #5c0020}
.cColumnMaxB	{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #ff00ff; border-color:#6c7170; background-color: #5c0020}
.cColumnMinB	{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #66ccff; border-color:#6c7170; background-color: #5c0020}
.cColumnPositiveB{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #00ff00; border-color:#6c7170; background-color: #5c0020}
.cColumnMinusB	{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #ff0000; border-color:#6c7170; background-color: #5c0020}
.cColumnFixedB	{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #f7ff31; border-color:#6c7170; background-color: #5c0020}
.cColumnDataB	{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #ffffff; border-color:#6c7170; background-color: #5c0020}	
.cColumnQuantiyB{font-family:arial; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #003062; border-color:#6c7170; background-color: #5c0020}

.cColumnTMediumB	{font-family:tahoma; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:bold;  color: #f7ff31; border-color:#6c7170; background-color: #5c0020}
.cColumnTMaxB	{font-family:tahoma; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:bold; color: #ff00ff; border-color:#6c7170; background-color: #5c0020}
.cColumnTMinB	{font-family:tahoma; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:bold; color: #66ccff; border-color:#6c7170; background-color: #5c0020}
.cColumnTPositiveB{font-family:tahoma; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:bold; color: #00ff00; border-color:#6c7170; background-color: #5c0020}
.cColumnTMinusB	{font-family:tahoma; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:bold; color: #ff0000; border-color:#6c7170; background-color: #5c0020}
.cColumnTFixedB	{font-family:tahoma; font-size:9pt; text-align:right; padding: 0 2 0 2; font-weight:bold; color: #f7ff31; border-color:#6c7170; background-color: #5c0020}

.cInfoLabel		{font-family:tahoma; font-size:8pt; text-align:left; padding: 0 2 0 2; font-weight:bold; color: #a5a3a3}
.cInfoValue1	{font-family:tahoma; font-size:8pt; text-align:left; padding: 0 2 0 2; font-weight:bold; color: #2b9700}
.cInfoValue2	{font-family:tahoma; font-size:8pt; text-align:left; padding: 0 2 0 2; font-weight:bold; color: #ee0000}

.cFeature		{font-family:tahoma; font-size:8pt; text-align:right; padding: 0 2 0 2; font-weight:normal; color: #860a01; text-decoration: none;}
.cFeatureText	{font-family:tahoma; font-size:8pt; text-align:left; padding: 0 2 0 2; font-weight:normal; color: #a5a3a3; text-decoration: none;}

.cCopyright		{font-family:tahoma; font-size:8pt; text-align:left; padding: 2 2 2 2; font-weight:normal; color: #a5a3a3; text-decoration: none; margin-top:4; margin-bottom:4}
.cCopyright1		{font-family:tahoma; font-size:9pt; text-align:left; padding: 2 2 2 2; font-weight:normal; color: #a5a3a3; text-decoration: none; margin-top:4; margin-bottom:4}

.TabSel 	{font-family: tahoma; font-size: 10pt; font-weight:bold; color: #e60000; text-align: center }
.TabUnSel {font-family: tahoma; font-size: 10pt; font-weight:normal; color: #a5a3a3; text-align: center}

.tbs, .tbu 	{font-family:arial; font-size: 10pt; font-weight:bold; vertical-align: middle; white-space:nowrap; height:20; cursor:pointer; text-align: center;}
.tbs 		{color: #e60000;}
.tbu		{color: #e4e0e0;}
.statusnormal {color:#FFF;font-family:Arial;font-size:9pt;font-weight:bold;}

/*-------Stock--------------------*/
.fl { float: left; }
.st-ul {list-style:none;margin:0px;padding:0px;width:100%;overflow:hidden;}
.st-li-hd {width:100%;margin:0px; padding:0px;overflow:hidden;}
.st-li-ho, .st-li-ho2 {width:94px;}
.st-li-ha, .st-li-ha2 {width:99px;}
.st-li-f {width:107px;}
.st-li-ho, .st-li-ha, .st-li-ho2, .st-li-ha2, .st-li-f {height:22px; margin:0px; padding:0px;text-align:center;}
.st-li-top5-title, .st-li-top5-tab, .st-li-tblPrice-title {height:20px; margin:0px; padding:0px;text-align:center;}
.st-li-top5-title {width:187px; background-image:url(/User/ck/Images/top5.gif)}
.st-li-top5-tab {width:113px; background-image:url(/User/ck/Images/top5_tab.gif)}
.st-li-top5-bottom {width:100%; height:5px; text-align:center; background:#f4f5f6 url(/User/ck/Images/top5_bt.gif) no-repeat top; overflow:hidden;}
.st-li-ho {background-image:url(/User/ck/Images/Bg-HOSE-01.gif)}
.st-li-ho2 {background-image:url(/User/ck/Images/Bg-HOSE-02.gif)}
.st-li-ha {background-image:url(/User/ck/Images/Bg-HASTC-01.gif)}
.st-li-ha2 {background-image:url(/User/ck/Images/Bg-HASTC-02.gif)}
.st-li-top5-title {background-image:url(/User/ck/Images/top5.gif)}
.st-li-top5-tab {background-image:url(/User/ck/Images/top5_tab.gif)}
.st-act {color: #8a0000;}
.st-deact {color: #898b8f;}
.st-act, .st-deact {margin-top:3px;margin-bottom:0px;font:bold 12px arial; cursor: pointer;}
.st-dt {text-align:center;font:12px arial;margin-top:2px;margin-bottom:0px;}
.hd-bdl {background:transparent url(/User/ck/Images/Bg-Left.gif) repeat-y top;}
.hd-bdr {background:transparent url(/User/ck/Images/Bg-Right.gif) repeat-y top; width: 0px;}
.hd-co {width:62px;}
.hd-tc {width:49px;}
.hd-tra {width:117px;}
.hd-med {width:100%;height:15px;margin-left: 0;}
.hd-pra {width:58px;height:15px;font:bold 12px arial; color:#ffffff;background:#af637d;text-align:center; margin-left: 0;}
.hd-ud {width:58px; margin-left: 0;}
.st-cont {width:294px;background:#ffffff;}
.hd-co, .hd-tc, .hd-med, .hd-ud {font:bold 12px arial; color:#ffffff; background:#9e224d; text-align:center;}
.hd-bdl { width: 0px; }
.hd-bdl, .hd-co, .hd-tc, .hd-tra, .hd-ud, .hd-bdr {height:31px;margin:0px;padding:0px;overflow:hidden;}
.hd-sp {font-size:1px;width:1px;background:#ffffff; margin-left: 0;}
.hd-sp2 {font-size:1px;width:100%;line-height:1px;height:1px;background:#ffffff; margin-left: 0;}
.hd-sp3 {font-size:1px;width:1px;}
.hd-tt {margin:7px 0px;}
.he37 {height:37px;}
.he31 {height:31px;}
.he22 {height:22px;}
.he191 {height:191px;}
.he20 {height:20px;}
.he9 {height:9px;}
.st-ft {height:9px;background:transparent url(/User/ck/Images/Bg-Footer.gif) no-repeat top;}
.hd-ho, .hd-top5-bd {background:transparent url(/Images/stock/background.gif) repeat-y top;}
.hd-ho {height:205px;}
.hd-dn {display:none;}
.hd-ind {height:20px;}
.hd-ind p {margin:3px 0px; margin-bottom:0px; padding-left:20px; font:9px arial; color:#646464;}
.hd-img {width:299px;height:297px;text-align:center}
.hd-img p{padding:0px 5px; margin-top:0px; margin-bottom: 5px;}
.hd-top5 {width:288px;padding:0px 5px;margin:0px;}
.hd-ft {height:45px;background:transparent url(/Images/stock/bg-bottom.gif) no-repeat top;}
.hd-de {width:140px;padding-top:5px;padding-left:10px;}
.stock-text{font-family: arial; font-size: 11px; color: #898b8f;}
.hd-da {background:transparent url(/Images/stock/bg-top.gif) repeat-x top;}
.Topactive{font-family: Arial; font-size:12px; color:#666666; font-weight:bold; border-bottom:#333333 2px solid;} 
.LbTop{font-family:Arial; font-size:11px; color: #666666}
.Topchange{font-family: Arial; font-size:11px; color:#000000;}
.changeindex{font-family:arial; font-size:11px; color:#000000;}
.LbTopMCK{font-family:arial; font-size:11px; color: #666666; text-decoration:none}
.LbTopMCK:link{font-family:arial; font-size:11px; color: #666666; text-decoration:none}
.LbTopMCK:hover{font-family:arial; font-size:11px; color: #666666; text-decoration: underline}
.dTop {height: 58px; width:270px; padding-left:5px; padding-right:15px; overflow:auto; overflow-x:hidden;}
.dlistitem {margin-bottom: 5px;}
.Index0 {color:#000000;font:bold 8pt tahoma;}
.Index1 {color:#0000ff;font:bold 8pt tahoma;}
.ForumSubjectLink {color:#0033ff;font:12px Arial; text-decoration:none;}
.ForumSubjectLink:visited {color:#000;}
.Paging {font:bold 8pt arial; text-decoration:none;}
.Red {color:#646464;}

.TopGoldActive { font-family: Arial; font-size:11px; color:#666666; border-bottom:#333333 2px solid; font-weight:bold;}
.st-li-tblPrice-title { width:187px; background-image:url('/Images/banggia.gif'); }
.st-li-top1-gp-bottom {width:100%; height:5px; text-align:center; background:#f4f5f6 url('/Images/top1_bt_gp.gif') no-repeat top; overflow:hidden;}
.hd-top1-gp { width:288px;padding:0px 5px;margin:0px;background:transparent url('/Images/top1_ct_gp.gif') no-repeat bottom; }

.tn-top, .tn-bottom {min-height:130px; overflow:hidden;}
.tn-top {background:url('/Images/Background/tn-top.gif') repeat-x top; margin-bottom: 5px;}
.tn-bottom {background:url('/Images/Background/tn-bottom.gif') repeat-x bottom; padding:20px 8px;}
.clsTestQuestion {font-weight:bold; color:#083b74;}
.tn-option {padding-left:5px; padding-bottom:10px;}
.tn-option p{margin-top:0px; margin-bottom:3px;}
.tn-result {border:#989a95 1px solid; margin-top:10px;}
.tn-point {padding:5px; border-bottom:#989a95 1px solid; background-color:#d72427; font:12px arial; color:#ffffff;}
.tn-detail {padding:5px; background-color:#ebebeb;}
</style>