<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id$
 */
?>
<div style="clear: both;">
	<table width="300" cellspacing="1" cellpadding="3" border="0" bgcolor="#2c5858">
		<tbody>
			<tr>
				<td align="center" class="AdTitle" colspan="2"><font color="#ffffff"><?php echo $this->translator()->widget('most_viewed'); ?></font></td>
			</tr>
			<?php foreach ($this->articles as $index => $article) : ?>
			<tr>
				<td bgcolor="#ffffff" class="Normal"<?php if (null == $article->image_square) : ?> colspan="2"<?php endif; ?>><a class="BoxLink" href="<?php echo $this->url($article->getProperties(), 'news_article_details'); ?>"><?php echo $this->escape($article->title); ?></a></td>
				<?php if ($article->image_square != null) : ?><td width="70" bgcolor="#ffffff"><a class="" href="<?php echo $this->url($article->getProperties(), 'news_article_details'); ?>"><img width="75" height="50" border="1" src="<?php echo $article->image_square; ?>"></a></td><?php endif; ?>
			</tr>
			<?php endforeach; ?>
			<tr>
				<td class="BreakLine" colspan="2"><font color="#ffffff"> </font></td>
			</tr>
		</tbody>
	</table>
</div>