<img alt="" class="img-weather" src="http://vnexpress.net/Images/Weather/<?php echo $this->adimg; ?>" />
<img alt="" class="img-weather" src="http://vnexpress.net/Images/Weather/<?php echo $this->adimg1; ?>" /> 
<img alt="" class="img-weather" src="http://vnexpress.net/Images/Weather/<?php echo $this->adimg2; ?>" /> 
<img alt="" class="img-weather" src="http://vnexpress.net/Images/Weather/c.gif" />
<p><?php echo $this->weather; ?></p>
<br><br><br><br><br>
<p>Ngu&#7891;n: vnexpress.net</pt>