<div style="padding-bottom: 5px;">
	<div class="fmenu-top">
		<div class="fl"><img src="<?php echo $this->APP_STATIC_SERVER; ?>/skin/<?php echo $this->APP_TEMPLATE; ?>/<?php echo $this->APP_SKIN; ?>/images/vne-small.gif" alt=""></div>
		<div class="fmenu-home fl">						
			<script type="text/javascript" language="javascript">
				document.write('<span style="padding-top:8px;"><a href="' +  menu_path[0] + '">TRANG CHỦ</a></span>');
			</script>						
		</div>
		<div class="sep-fmenu fl">&nbsp;</div>
		<div class="sep-fmenu fl">&nbsp;</div>
		<div class="fmenu-other fl">
			<a class="link-contact" href="http://lienhe.thoibaonganhang.vn/" target="mail"> Mail gửi Toà soạn</a>		</div>
		<div class="sep-fmenu fl">&nbsp;</div>
		
		<div class="fmenu-other fl">
			<a class="link-contact" href="http://lienhe.thoibaonganhang.vn/" target="_blank"> Liên hệ quảng cáo</a>		</div>
		<div class="sep-fmenu fl">&nbsp;</div>
		<!--
		<div class="fmenu-other fl">
			<a class="link-contact" href="http://unnet.vn" target="_blank"> Việc làm tại TBNH</a>		</div>
		 -->
		<div class="sep-fmenu fl">&nbsp;</div>
		<div class="fmenu-other fl">Đường dây nóng: (04)3.7163923		</div>                    
	</div>
	<div class="fmenu-bottom">					
		<script type="text/javascript" language="javascript">
			writeFooterMenu(); //ShowFixFloatBanner(0);ShowFixFloatBanner(2);ShowFixFloatBanner(1);ShowFixFloatBanner(3);
			//ShowSlideBanner();
		</script>
	</div>
	<div class="copyright">
	<center>
		<p>Thời báo Ngân hàng - Cơ quan của Ngân hàng Nhà nước Việt Nam <br>
			Giấy phép số : 223.GP-TTĐT ngày 19/12/2011.<br>
			Tổng biên tập: NGUYỄN LAN ANH<br>
			Địa chỉ: 137 Phố Yên Phụ - Quận Tây Hồ - TP Hà Nội.<br>
			ĐT:(04)3.7163922 - (04)3.7163923. Fax:(04)3.7163921.<br>
			Email: baomangnganhang@gmail.com</p>
			<!-- Histats.com  START  (standard)-->
<script type="text/javascript">document.write(unescape("%3Cscript src=%27http://s10.histats.com/js15.js%27 type=%27text/javascript%27%3E%3C/script%3E"));</script>
<a href="http://www.histats.com" target="_blank" title="track hits" ><script  type="text/javascript" >
try {Histats.start(1,2174002,4,22,130,30,"00000010");
Histats.track_hits();} catch(err){};
</script></a>
<noscript><a href="http://www.histats.com" target="_blank"><img  src="http://sstatic1.histats.com/0.gif?2174002&101" alt="track hits" border="0"></a></noscript>
<!-- Histats.com  END  -->
	</center>
	</div>
</div>           