<div id="logoEH" class="logo fl">
	<a onFocus="this.blur()" hidefocus="" href="<?php echo $this->APP_URL; ?>"><img class="img-logo" src="<?php echo $this->APP_STATIC_SERVER; ?>/skin/<?php echo $this->APP_TEMPLATE; ?>/<?php echo $this->APP_SKIN; ?>/images/logo.jpg" alt=""></a>					
</div>
<div class="topbanner fr" id="topbannerEH">
	<table cellspacing="0" cellpadding="0" border="0" style="width: 100%;">
		<tbody>
			<tr>
				<td style="vertical-align: middle;">							
					<div class="halfbanner fl">
						<table width="364" cellspacing="0" cellpadding="0" border="0" align="center">
							<tbody>
								<tr>
									<td>
										<div style="position: absolute; overflow: hidden; z-index: 100; top: 38px; width: 330px; height: 90px;" id="t_g_ad_h1">
											<script type="text/javascript"> 
												$(document).ready(function() {
													(new Tomato.Ad.Loader('H1', 't_g_ad_h1', '')).load();
												});
											</script>
										</div>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
					<div class="halfbanner fr">
						<table width="364" cellspacing="0" cellpadding="0" border="0" align="center">
							<tbody>
								<tr>
									<td>
										<div style="position: absolute; overflow: hidden; z-index: 100; top: 38px; right: 0px; width: 330px; height: 90px;" id="t_g_ad_h2">
											<script type="text/javascript"> 
												$(document).ready(function() {
													(new Tomato.Ad.Loader('H2', 't_g_ad_h2', '')).load();
												});
											</script>
										</div>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
				</td>                           
			</tr>
		</tbody>
	</table>
</div>
			